language: node_js
node_js:
- 0.10.36
script:
- npm test

env:
  global:
    secure: olXRM1pAU082pFozpvHbdSZ/3lBQSj2L+gHthygU9IxcKhvVP88dQNTjoZrjbCRfG2cxgXccbEjp+cjNNgpYSOeSUtEgVf84M4aTfDr74NVvmsHbTroQT4Jb3lvJTdgJuBSy6JlX1mnlE1l0nDEWqUBTRC3VNWF3BYWiu4iy9CLy9LW2NJ1VRElpmT6FBuxtw698ofww86Hly76frWlP2s4FMEFgKBI0N9+0IKkIii5qYJ5NE06BOeFRUGhK8ir6HA+iOF/VoTop8+ttIYZvnHmr7VG/3T4LNBCszRHNoqwAXAd13sWrwlgqxSxcOlaSfjvRBvm9XoHe9yUTAfKoRNJJSQTe7LbGdZVt8A1KaNalwCA5n135o3Y7WsbKVGSBm87zOeKLQNZhX7tkJ/qdZETlG4rB6c8U0eIcbbGkOMb6OVcpgZmbb2Fr5ybU6eSVpn9OZI3w2H1WOaBT6jhB2Ww05wXxmheZ0sdcGhSw536CaDEjo93b2HtHLG/9txBvhnVfTJECwp3IWvT9BOgHqgixKR7AM+bkkmGvGrQSeeynqjwrP9Vxk4eOhL9cGw2oeelaIRsulLhBvPRClFVSEtXt2TwN8C/xFTl+RUQE5kL3A4IU0G+nH02tnoO4PaUZsxPMQV+e/h7VTane1369UMduRRELhRqVVc8AEX8FGxs=
